sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t finir/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run finir/client-test npm run test -- --coverage

after_success:
  - docker build -t finir/multi-client -f ./client/Dockerfile ./client
  - docker build -t finir/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t finir/multi-server -f ./server/Dockerfile ./server
  - docker build -t finir/multi-worker -f ./worker/Dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push finir/multi-client
  - docker push finir/multi-nginx
  - docker push finir/multi-server
  - docker push finir/multi-worker
