sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dltruongc/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dltruongc/client-test npm run test -- --coverage

after_success:
  - docker build -t dltruongc/multi-client -f ./client/Dockerfile ./client
  - docker build -t dltruongc/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t dltruongc/multi-server -f ./server/Dockerfile ./server
  - docker build -t dltruongc/multi-worker -f ./worker/Dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push dltruongc/multi-client
  - docker push dltruongc/multi-nginx
  - docker push dltruongc/multi-server
  - docker push dltruongc/multi-worker
